FROM ghcr.io/mark3labs/mcp-filesystem-server:latest

LABEL maintainer="Jason Matherly <jason@matherly.net>"
LABEL description="Demo MCP filesystem Server"
LABEL version="1.0.0"
LABEL original-image="ghcr.io/mark3labs/mcp-filesystem-server:latest"

# Set environment variables
ENV LOG_LEVEL=info
