# Prometheus configuration for MCP Platform monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Load alert rules
rule_files:
  - "/etc/prometheus/alerts/*.yml"

# Scrape configuration
scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # MCP Platform Gateway monitoring
  - job_name: "mcp-gateway"
    static_configs:
      - targets: ["mcp-gateway:8080"]
    metrics_path: "/gateway/metrics"
    scrape_interval: 30s

  # PostgreSQL monitoring (if pg_exporter is added)
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]
    scrape_interval: 60s

  # Redis monitoring (if redis_exporter is added)
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 60s

  # Nginx monitoring (if nginx_exporter is added)
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:80"]
    scrape_interval: 60s

  # Node exporter for system metrics (if added)
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 60s
